import time
adjective1=input("Give me an adjective:")
time.sleep(1)
print()
adjective2=input("One more adjective please:")
time.sleep(1)
print()
bird=input("Name a type of bird:")
time.sleep(1)
print()
room=input("Name a room in a house:")
time.sleep(1)
print()
verbpasttense=input("I need a verb that is past tense:")
time.sleep(1)
print()
verb=input("Now i need a verb:")
time.sleep(1)
print()
rname=input("Give me one of your relatives names:")
time.sleep(1)
print()
noun=input("I need a noun now:")
time.sleep(1)
print()
liquid=input("Now im going to need a liquid:")
time.sleep(1)
print()
ingverb=input("I need a verb ending in -ing:")
time.sleep(1)
print()
body=input("Name a part of the body also it must be plural:")
time.sleep(1)
print()
pnoun=input("Plural noun please:")
time.sleep(1)
print()
ingverb2=input("I need a verb ending in -ing:")
time.sleep(1)
print()
noun2=input("Give me a noun and we are done:")


print()
print()
print()
print()
print()
print()
print()
print()
print()
print(f"It was a {adjective1}, cold november day. I woke up to the {adjective2} smell of {bird} roasting in the {room} downstairs.  I {verbpasttense} down the stairs to see if i could help {verb} the dinner. My mom said, see if {rname} needs a fresh {noun}. so I carried a tray of glasses full of {liquid} into the {ingverb} room. when I got there, I couldn't believe my {body}! There were {pnoun} {ingverb2} on the {noun2}!!!!!!!!!!!!!!!!")
