import time
name=input("what is your name?")
time.sleep(1)
print("well hi there " +name+".")
time.sleep(1)
food=input("so "+name+" what is your favorite food?")
time.sleep(1)
whatfood=input("wow i have never tried " +food+" can you discribe it?")
time.sleep(1)
print("wow that sounds good")
time.sleep(1)
age=input("so how old are you " +name)
time.sleep(1)
print("ahhh so you are " +age+" i am 13")
time.sleep(1)
